#NET-SNMP-MIB,SNMPV2-SMI,SNMPV2-TC,
.1.3.6.1.4.1.8072.3.1.3,Lextm.SharpSnmpLib.Mib.ModuleIdentity,netSnmpMonitorMIB,netSnmpModuleIDs
.1.3.6.1.4.1.8072.1.21,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsProcess,netSnmpObjects
.1.3.6.1.4.1.8072.1.22,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsDisk,netSnmpObjects
.1.3.6.1.4.1.8072.1.23,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsFile,netSnmpObjects
.1.3.6.1.4.1.8072.1.24,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsLog,netSnmpObjects
