#SNMPV2-SMI,UCD-SNMP-MIB,
.1.3.6.1.4.1.2021.14,Lextm.SharpSnmpLib.Mib.ModuleIdentity,ucdDemoMIB,ucdavis
.1.3.6.1.4.1.2021.14.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,ucdDemoMIBObjects,ucdDemoMIB
.1.3.6.1.4.1.2021.14.1.1,Lextm.SharpSnmpLib.Mib.OidValueAssignment,ucdDemoPublic,ucdDemoMIBObjects
.1.3.6.1.4.1.2021.14.1.1.1,Lextm.SharpSnmpLib.Mib.ObjectType,ucdDemoResetKeys,ucdDemoPublic
.1.3.6.1.4.1.2021.14.1.1.2,Lextm.SharpSnmpLib.Mib.ObjectType,ucdDemoPublicString,ucdDemoPublic
.1.3.6.1.4.1.2021.14.1.1.3,Lextm.SharpSnmpLib.Mib.ObjectType,ucdDemoUserList,ucdDemoPublic
.1.3.6.1.4.1.2021.14.1.1.4,Lextm.SharpSnmpLib.Mib.ObjectType,ucdDemoPassphrase,ucdDemoPublic
