#include <gtest/gtest.h>
#include "../HIGHT_KISA.h"


void enc(
			 BYTE    *UserKey,       
			 BYTE    *Data)
{
	BYTE szRoundKey[KISA_HIGHT_ROUND_KEY_LEN] = {0};
	HIGHT_KeySched(UserKey, 0, szRoundKey);
	HIGHT_Encrypt(szRoundKey, Data);
}

void enc_dec(
			 BYTE    *UserKey,       
			 BYTE    *Data)
{
	BYTE szRoundKey[KISA_HIGHT_ROUND_KEY_LEN] = {0};
	HIGHT_KeySched(UserKey, 0, szRoundKey);
	HIGHT_Encrypt(szRoundKey, Data);
	HIGHT_Decrypt(szRoundKey, Data);
}

// {2BD0706A-887C-4bc2-BCDA-10A3F9E4C3F5} generated by guidgen.exe
BYTE szUserKey[] = {
	0x2b, 0xd0, 0x70, 0x6a, 0x88, 0x7c,
	0x4b, 0xc2, 0xbc, 0xda, 0x10, 0xa3, 0xf9, 0xe4, 0xc3, 0xf5
};

TEST(enc_dec, Returns_same)
{	
	BYTE dataOrigin[136] = "apple";
	BYTE dataEncDec[136] = "apple";
	enc_dec(szUserKey, dataEncDec);

	ASSERT_EQ( 0, memcmp(dataOrigin, dataEncDec, sizeof(dataOrigin)) );
}

TEST(enc, Returns_diff)
{
	BYTE dataOrigin[] = "appleapple";
	BYTE dataEncDec[] = "appleapple";
	enc(szUserKey, dataEncDec);

	ASSERT_NE( 0, memcmp(dataOrigin, dataEncDec, sizeof(dataOrigin)) );
}