#NET-SNMP-MIB,NET-SNMP-TC,SNMPV2-SMI,SNMPV2-TC,
.1.3.6.1.4.1.8072.3.1.4,Lextm.SharpSnmpLib.Mib.ModuleIdentity,netSnmpSystemMIB,netSnmpModuleIDs
.1.3.6.1.4.1.8072.1.31,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsMemory,netSnmpObjects
.1.3.6.1.4.1.8072.1.32,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsSwap,netSnmpObjects
.1.3.6.1.4.1.8072.1.33,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsCPU,netSnmpObjects
.1.3.6.1.4.1.8072.1.34,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsLoad,netSnmpObjects
.1.3.6.1.4.1.8072.1.35,Lextm.SharpSnmpLib.Mib.OidValueAssignment,nsDiskIO,netSnmpObjects
